masas/controllers/account.py
from flask import (
     Blueprint, flash, render_template, redirect, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash
from masas import authorize
from masas.enums import UserRole
from masas.forms import ChangePasswordForm
from masas.models.user import User
from masas.repositories.userrepo import UserRepository

bp = Blueprint('account', __name__, template_folder='templates')
user_repo = UserRepository()


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        login = request.form['login']
        password = request.form['password']

        user = user_repo.get_by_login(login)

        if user is None or not check_password_hash(user.password, password):
            flash('Usuario o contraseña incorrectos')
        else:
            session.clear()
            session['user_id'] = user.id
            session['user_login'] = user.login
            session['user_role'] = UserRole.from_value(user.role).name
            return redirect(url_for('index'))

    return render_template('login.html')


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))


@bp.route('/changepassword', methods=['GET', 'POST'])
@authorize()
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = user_repo.get_by_id(session['user_id'])

        if not check_password_hash(user.password, form.password.data):
            flash('La contraseña actual es incorrecta')
        else:
            new_password = form.new_password.data
            user.password = generate_password_hash(new_password)
            user_repo.persist(user)

            return redirect(url_for('index'))

    return render_template('changepassword.html', form=form)

masas/controllers/movimientos.py
from flask import (
     Blueprint, flash, current_app, jsonify, render_template,
     redirect, request, session, url_for
)
from weasyprint import HTML
import masas.enums
from masas import authorize
from masas.core.observers import CreateObserver, DeleteObserver
from masas.enums import ESPACIAMIENTOS, UserRole
from masas.forms import MovimientoForm
from masas.models.movimiento import (
    Movimiento, Localizacion, Mapa, Foto, Actividad, Distribucion, Litologia,
    Clasificacion, Morfometria, Causa, CoberturaSuelo, UsoSuelo,
    EfectoSecundario, Dano)
from masas.repositories.movimientorepo import MovimientoRepository

bp = Blueprint('movimientos', __name__, template_folder='templates')
mov_repo = MovimientoRepository()


@bp.route('/movimientos')
@authorize()
def index():
    if not request.is_xhr:
        return render_template('movimientos/index.html')

    search = request.args.get('queries[search]', '')
    limit = request.args.get('perPage', 0)
    offset = request.args.get('offset', 0)

    movimientos = mov_repo.get_list(search, limit, offset)

    def format_mov(mov):
        return {
            'id': mov.id,
            'encuestador': mov.encuestador,
            'fecha': mov.fecha.strftime('%Y-%m-%d'),
            'institucion': mov.institucion,
            'codigo': mov.codigo,
            'usuario': mov.usuario.name
        }

    return jsonify({
        'registros': [format_mov(m) for m in movimientos[1]],
        'total': movimientos[0]
    })


@bp.route('/movimientos/create', methods=['GET', 'POST'])
@authorize(UserRole.user)
def create():
    form = MovimientoForm(request.form)

    if request.method == 'POST' and form.validate():
        mov = Movimiento()
        mov.localizacion = Localizacion()
        mov.localizacion.mapas = []
        mov.localizacion.fotos = []
        mov.actividad = Actividad()
        mov.actividad.distribucion = Distribucion()
        mov.litologia = Litologia()
        mov.litologia.detalles = []
        mov.clasificacion = Clasificacion()
        mov.morfometria = Morfometria()
        mov.causa = Causa()
        mov.cobertura_suelo = CoberturaSuelo()
        mov.uso_suelo = UsoSuelo()
        mov.documentos_ref = []
        mov.efecto_secundario = EfectoSecundario()
        mov.dano = Dano()
        mov.dano.detalles = []

        form.populate_obj(mov)

        mov.usuario_id = session['user_id']

        mov_repo.persist(mov)

        observer = CreateObserver()
        mov.suscribe(observer)
        mov.notify(session['user_login'])

        return redirect(url_for('.index'))

    return render_template('movimientos/form.html',
                           form=form,
                           espaciamientos=ESPACIAMIENTOS)


@bp.route('/movimientos/edit/<int:id>', methods=['GET', 'POST'])
@authorize(UserRole.user)
def edit(id):
    mov = Movimiento.query.filter(Movimiento.id == id).first()
    formData = request.form if request.method == 'POST' else None
    form = MovimientoForm(formData, obj=mov)

    if request.method == 'POST' and form.validate():
        form.populate_obj(mov)

        mov_repo.persist(mov)

        return redirect(url_for('.index'))

    return render_template('/movimientos/form.html',
                           form=form,
                           espaciamientos=ESPACIAMIENTOS)


@bp.route('/movimientos/delete/<int:id>', methods=['POST'])
@authorize(UserRole.user)
def delete(id):
    mov = mov_repo.get_by_id(id)

    mov_repo.delete(mov)

    observer = DeleteObserver()
    mov.suscribe(observer)
    mov.notify(session['user_login'])

    return redirect(url_for('.index'))


@bp.route('/movimientos/view/<int:id>')
@authorize()
def view(id):
    movimiento = mov_repo.get_by_id(id)

    return render_template('/movimientos/view.html',
                           mov=movimiento,
                           enums=masas.enums)


@bp.route('/movimientos/download/<int:id>')
@authorize()
def download(id):
    movimiento = mov_repo.get_by_id(id)

    output_html = render_template('/movimientos/view.html',
                                  mov=movimiento,
                                  enums=masas.enums)

    styles = ['./masas/static/css/print.css']

    pdf = HTML(string=output_html).write_pdf(stylesheets=styles)

    response = current_app.response_class(pdf, mimetype='application/pdf')

    response.headers.add('Content-Disposition',
                         'attachment',
                         filename='movimiento-' + movimiento.codigo + '.pdf')

    return response

masas/controllers/users.py
from flask import (
     Blueprint, flash, jsonify, render_template, redirect, request, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash
from masas import authorize
from masas.enums import UserRole
from masas.models.user import User
from masas.core.database import db_session
from masas.forms import UserForm
from masas.repositories.userrepo import UserRepository


bp = Blueprint('users', __name__, template_folder='templates')
user_repo = UserRepository()


@bp.route('/users')
@authorize(UserRole.admin)
def index():
    if not request.is_xhr:
        return render_template('users/index.html')

    search = request.args.get('queries[search]', '')
    limit = request.args.get('perPage', 0)
    offset = request.args.get('offset', 0)

    users = user_repo.get_list(search, limit, offset)

    def format_user(user):
        role = UserRole.from_value(user.role)
        return {
            'id': user.id,
            'login': user.login,
            'name': user.name,
            'role': role.value[1]
        }

    return jsonify({
        'registros': [format_user(u) for u in users[1]],
        'total': users[0]
    })


@bp.route('/users/create', methods=['GET', 'POST'])
@authorize(UserRole.admin)
def create():
    form = UserForm(request.form)
    form.user_id = 0

    if request.method == 'POST' and form.validate():
        usr = User()
        form.populate_obj(usr)

        usr.password = generate_password_hash(usr.password)
        user_repo.persist(usr)

        return redirect(url_for('.index'))

    return render_template('/users/form.html', form=form)


@bp.route('/users/edit/<int:id>', methods=['GET', 'POST'])
@authorize(UserRole.admin)
def edit(id):
    user = User.query.filter(User.id == id).first()

    formData = request.form if request.method == 'POST' else None
    form = UserForm(formData, obj=user)
    form.user_id = id

    if request.method == 'POST' and form.validate():
        form.populate_obj(user)

        user.password = generate_password_hash(user.password)
        user_repo.persist(user)

        return redirect(url_for('.index'))

    return render_template('/users/form.html', form=form, id=id)


@bp.route('/users/delete/<int:id>', methods=['POST'])
@authorize(UserRole.admin)
def delete(id):
    usr = user_repo.get_by_id(id)
    user_repo.delete(usr)

    return redirect(url_for('.index'))

masas/templates/changepassword.html
{%extends '/layout.html'%}
{% import 'helpers.html' as helpers %}
{%block title%}Cambiar mi contraseña{%endblock%}
{%block body%}    
    <h3>Cambiar mi contraseña</h1>

    {{ helpers.error_summary() }}

    <form method="POST">
        <div class="grid-x grid-padding-x">
            <div class="large-2 cell">
                <label for="middle-label" class="text-right middle">Contraseña actual</label>
            </div>
            <div class="large-3 cell">
                {{ helpers.input(form.password) }}
            </div>
        </div>
    
        <div class="grid-x grid-padding-x">
            <div class="large-2 cell">
                <label for="middle-label" class="text-right middle">Nueva contraseña</label>
            </div>
            <div class="large-3 cell">
                {{ helpers.input(form.new_password) }}
            </div>
        </div>
    
        <div class="grid-x grid-padding-x">
            <div class="large-2 cell">
                <label for="middle-label" class="text-right middle">Confirma la contraseña</label>
            </div>
            <div class="large-3 cell">
                {{ helpers.input(form.confirm_password) }}
            </div>
        </div>
        
        <div class="grid-x grid-padding-x">
            <div class="large-3 large-offset-2 cell">
                <a href="{{ url_for('index') }}" class="secondary button">Cancelar</a>
                <button type="submit" class="button">Guardar</button>
            </div>
        </div>
    </form> 
{%endblock%}

masas/templates/helpers.html
{%- macro input(control) %}
    {{ control(**kwargs) }}                
    {% if control.errors %}
        <ul class="error-msg">
            {% for error in control.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}

{%- macro input_errors(control) %}
    {% if control.errors %}
        {% for error in control.errors %}
                <label class="error" for="{{ control.name }}">{{ error }}</label>
        {% endfor %}        
    {% endif %}
{% endmacro %}

{%- macro error_summary() %}
    {% with errors = get_flashed_messages() %}
        {% if errors %}
            <ul class="error-msg callout alert">
            {% for error in errors  %}
                <li>{{ error }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
{% endmacro %}

masas/templates/index.html
{%extends '/layout.html'%}
{%block title%}Inicio{%endblock%}
{%block body%}
    <div class="content">
        <h3>Bienvenid@</h3>
    </div>
{%endblock%}

masas/templates/layout.html
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="/static/css/foundation.min.css">  
  {% block styles %}{% endblock %}
  <link rel="stylesheet" href="/static/css/app.css">
</head>

<body>
  <div class="title-bar" data-responsive-toggle="main-navigation" data-hide-for="medium">
    <div class="title-bar-left">
      <button class="menu-icon" type="button" data-toggle="main-navigation"></button>
      <div class="title-bar-title">Menu</div>
    </div>
    <div class="title-bar-right">Movimientos</div>
  </div>
  <div class="top-bar" id="main-navigation">
    <div class="top-bar-left">
      <ul class="menu vertical medium-horizontal">
        <li class="menu-text hide-for-small-only brand">Movimientos</li>
        {% if session['user_id'] %}
          {% if session['user_role'] == 'admin' %}
            <li><a href="{{ url_for('users.index') }}">Usuarios</a></li>
          {% endif %}
          <li><a href="{{ url_for('movimientos.index') }}">Formularios</a></li>
        {% endif %}
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu vertical medium-horizontal">
        {% if session['user_id'] %}
          <li>
            <ul class="dropdown menu" data-dropdown-menu>
              <li>
                <a href="#">{{ session['user_login'] }}</a>
                <ul class="menu">
                  <li><a href="{{ url_for('account.change_password') }}">Cambiar contraseña</a></li>
                  <li><a href="{{ url_for('account.logout') }}">Salir</a></li>
                </ul>
              </li>
            </ul>
          </li>
        {% else %}
          <li><a href="{{ url_for('account.login') }}">Ingresar</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  
  <div id="main-content">
    {% block body %}{% endblock %}
  </div>

  <script src="/static/js/vendor/jquery.js"></script>
  <script src="/static/js/vendor/foundation.min.js"></script>
  <script src="/static/js/app.js"></script>
  {% block scripts %}{% endblock %}
</body>
</html>

masas/templates/layoutempty.html
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <!--link rel="stylesheet" href="/static/css/foundation.min.css"-->
    <!--link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.min.css') }}"-->
    
    {%block styles %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

masas/templates/login.html
{%extends '/layout.html'%}
{% import 'helpers.html' as helpers %}
{%block title%}Iniciar sesión{%endblock%}
{%block body%}    
    <div class="grid-x">
        <div class="cell small-12 large-4 large-offset-4">
            <h3 class="text-center">Iniciar sesión</h1>
            {{ helpers.error_summary() }}

            <form method="POST">
                <div>
                    <label>Login</label>
                    <input type="text" name="login">                        
                </div>
                <div>
                    <label>Contraseña</label>
                    <input type="password" name="password">                        
                </div>
                
                <div class="text-center">
                    <button type="submit" class="button">Ingresar</button>
                </div>                    
            </form>
        </div>
    </div>    
{%endblock%}